language: go
dist: focal
jobs:
  include:
    - stage: test
      name: "Go 1.23"
      go:
        - 1.23.x
      install: skip
      script:
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
